version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: '186396'
      MYSQL_DB: 'login_system'
      MYSQL_PORT: 3306
    volumes:
      - ./backend:/app
    networks:
      - mvp_scout_network
    depends_on:
      - mysql
    restart: always  # Reiniciar automaticamente em caso de falha

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    networks:
      - mvp_scout_network
    depends_on:
      - backend  # Certifique-se de que o frontend aguarda o backend estar pronto
    restart: always  # Reiniciar automaticamente em caso de falha

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '186396'
      MYSQL_DATABASE: 'login_system'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mvp_scout_network
    restart: always  # Reiniciar automaticamente em caso de falha

networks:
  mvp_scout_network:
    driver: bridge

volumes:
  db_data:
